services:

    Abc\JobServerBundle\Controller\CronJobController:
        public: true
        arguments:
            - '@abc.job.base_cronjob_controller'

    abc.job.base_cronjob_controller:
        class: Abc\Job\Controller\CronJobController
        public: true
        arguments:
            - '@abc.job.cronjob_manager'
            - '@abc.job.job_server'
            - '@abc.job.validator'
            - '@logger'

    abc.job.cronjob_manager:
        public: true
        class: 'Abc\Job\CronJobManager'
        arguments:
            - '@abc.job.cronjob_entity_manager'

    abc.job.cronjob_entity_manager:
        class: 'Abc\Job\Doctrine\CronJobManager'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Abc\Job\Model\CronJob'

    abc.job.schedule_provider:
        class: Abc\Job\Schedule\ScheduleProvider
        arguments:
            - '@abc.job.cronjob_manager'
        tags:
            - { name: 'abc.scheduler.schedule_provider' }

    abc.job.schedule_processor:
        class: Abc\Job\Schedule\ScheduleProcessor
        arguments:
            - '@abc.job.job_server'
        tags:
            - { name: 'abc.scheduler.schedule_processor', provider: 'abc.job.schedule_provider' }
